version: "3.8"
services:
  livemarket-database:
    container_name: livemarket-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: devhyuk214/livemarket-database
    environment:
      - MARIADB_DATABASE=livemarket
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"