spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/livemarket
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size:
        30MB
      max-file-size:
        10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_EMAIL}
    password: ${SPRING_EMAIL_PASSWORD}
    properties:
      mail:
       smtp:
         auth:
           true
         timeout:
           5000
         starttls.enable:
           true

com:
  market:
    upload:
      path:
        upload